const Symbols = [
    'NSE:NESTLEIND-EQ',
    'NSE:BAJAJFINSV-EQ',
    'NSE:NTPC-EQ',
    'NSE:ITC-EQ',
    'NSE:HINDOILEXP-EQ',
    'NSE:POWERGRID-EQ',
    'NSE:LTIM-EQ',
    'NSE:ADANIPORTS-EQ',
    'NSE:TATAMOTORS-EQ',
    'NSE:INDUSINDBK-EQ',
    'NSE:HCL-INSYS-EQ',
    'NSE:COALINDIA-EQ',
    'NSE:ICICIBANK-EQ',
    'NSE:JSWSTEEL-EQ',
    'NSE:TATASTEEL-EQ',
    'NSE:TECHM-EQ',
    'NSE:TATACONSUM-EQ',
    'NSE:HINDALCO-EQ',
    'NSE:WIPRO-EQ',
    'NSE:HDFCBANK-EQ',
    'NSE:EICHERMOT-EQ',
    'NSE:ESCORTS-EQ',
    'NSE:GAEL-EQ',
    'NSE:GAIL-EQ',
    'NSE:GENESYS-EQ',
    'NSE:HAVELLS-EQ',
    'NSE:HGS-EQ',
    'NSE:INOXGREEN-EQ',
    'NSE:JIOFIN-EQ',
    'NSE:MEDANTA-EQ',
    'NSE:MITTAL-EQ',
    'NSE:NDTV-EQ',
    'NSE:RAMASTEEL-EQ',
    'NSE:ZOMATO-EQ',
    'NSE:TVTODAY-EQ',
    'NSE:VAISHALI-EQ',
    'NSE:NIFTYBANK-INDEX',
    'NSE:NIFTY50-INDEX'
  ];


 const CommoditySymbols = ['NSE:NIFTYBANK-INDEX', 'NSE:NIFTY50-INDEX', 'MCX:CRUDEOIL23DECFUT', 'MCX:GOLD24FEBFUT', 'MCX:CRUDEOILM23DECFUT', 'MCX:MCXMETLDEX23DECFUT', 'MCX:NATGASMINI23DECFUT', 'MCX:NATURALGAS23DECFUT', 'MCX:MENTHAOIL23DECFUT', 'MCX:ALUMINIUM23DECFUT', 'MCX:COPPER23DECFUT', 'MCX:LEAD23DECFUT', 'MCX:NICKEL23DECFUT', 'MCX:ZINC23DECFUT', 'MCX:ALUMINI23DECFUT', 'MCX:LEADMINI23DECFUT', 'MCX:ZINCMINI23DECFUT', 'MCX:GOLDGUINEA23DECFUT', 'MCX:GOLDPETAL23DECFUT','MCX:CRUDEOIL24JANFUT', 'MCX:GOLD24FEBFUT', 'MCX:CRUDEOILM24JANFUT', 'MCX:MCXMETLDEX24JANFUT', 'MCX:NATGASMINI24JANFUT', 'MCX:NATURALGAS24JANFUT', 'MCX:MENTHAOIL24JANFUT', 'MCX:ALUMINIUM24JANFUT', 'MCX:COPPER24JANFUT', 'MCX:LEAD24JANFUT', 'MCX:NICKEL24JANFUT', 'MCX:ZINC24JANFUT', 'MCX:ALUMINI24JANFUT', 'MCX:LEADMINI24JANFUT', 'MCX:ZINCMINI24JANFUT', 'MCX:GOLDGUINEA24JANFUT', 'MCX:GOLDPETAL24JANFUT','MCX:CRUDEOIL24FEBFUT', 'MCX:GOLD24FEBFUT', 'MCX:CRUDEOILM24FEBFUT', 'MCX:MCXMETLDEX24FEBFUT', 'MCX:NATGASMINI24FEBFUT', 'MCX:NATURALGAS24FEBFUT', 'MCX:MENTHAOIL24FEBFUT', 'MCX:ALUMINIUM24FEBFUT', 'MCX:COPPER24FEBFUT', 'MCX:LEAD24FEBFUT', 'MCX:NICKEL24FEBFUT', 'MCX:ZINC24FEBFUT', 'MCX:ALUMINI24FEBFUT', 'MCX:LEADMINI24FEBFUT', 'MCX:ZINCMINI24FEBFUT', 'MCX:GOLDGUINEA24FEBFUT', 'MCX:GOLDPETAL24FEBFUT'];


 module.exports  = {CommoditySymbols, Symbols}